spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
    include-binding-errors: always

fullcart:
  product-service:
    port: ${PRODUCT_SERVICE_PORT}
