version: '3'

services:

  webshop-service-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    #    expose:
    #      - 3306
    networks:
      proxy:
        aliases:
          - db
    volumes:
      - webshop-service-db-mysql:/var/lib/mysql

  webshop-service:
    container_name: webshop-service
    image: webshop-service:1.0-SNAPSHOT
    restart: on-failure
    depends_on:
      - webshop-service-db
    ports:
      - 80:8080
    networks:
      - proxy
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}

volumes:
  webshop-service-db-mysql:

networks:
  proxy:

