server:
  error:
    include-message: always
    include-binding-errors: always

fullcart:
  product-service:
    host: ${PRODUCT_SERVICE_HOST}
    port: ${PRODUCT_SERVICE_PORT}
  user-service:
    host: ${USER_SERVICE_HOST}
    port: ${USER_SERVICE_PORT}
  buying-service:
    host: ${BUYING_SERVICE_HOST}
    port: ${BUYING_SERVICE_PORT}

